name: telecomChurn
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - _py-xgboost-mutex=2.0
  - asttokens=2.0.5
  - backcall=0.2.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - colorama=0.4.4
  - contourpy=1.0.5
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - fonttools=4.37.3
  - freetype=2.12.1
  - intel-openmp=2022.1.0
  - ipykernel=6.9.1
  - ipython=8.3.0
  - jedi=0.18.1
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - kiwisolver=1.4.4
  - lcms2=2.12
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libdeflate=1.14
  - libffi=3.4.2
  - liblapack=3.9.0
  - libpng=1.6.38
  - libsqlite=3.39.3
  - libtiff=4.4.0
  - libwebp-base=1.2.4
  - libxcb=1.13
  - libxgboost=1.6.2
  - libzlib=1.2.12
  - lightgbm=3.3.2
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - matplotlib-base=3.6.0
  - matplotlib-inline=0.1.2
  - mkl=2022.1.0
  - msys2-conda-epoch=20160418
  - munkres=1.1.4
  - nest-asyncio=1.5.5
  - networkx=2.8.6
  - numpy=1.23.3
  - openjpeg=2.5.0
  - openssl=3.0.5
  - packaging=21.3
  - pandas=1.5.0
  - parso=0.8.3
  - patsy=0.5.2
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.2.2
  - prompt-toolkit=3.0.20
  - pthread-stubs=0.4
  - pure_eval=0.2.2
  - py-xgboost=1.6.2
  - pygments=2.11.2
  - pyparsing=3.0.9
  - python=3.10.6
  - python-dateutil=2.8.2
  - python_abi=3.10
  - pytz=2022.2.1
  - pywin32=302
  - pyzmq=22.3.0
  - scikit-learn=1.1.2
  - scipy=1.9.1
  - seaborn=0.12.0
  - seaborn-base=0.12.0
  - setuptools=65.3.0
  - six=1.16.0
  - stack_data=0.2.0
  - statsmodels=0.13.2
  - tbb=2021.5.0
  - threadpoolctl=3.1.0
  - tk=8.6.12
  - tornado=6.1
  - traitlets=5.1.1
  - typing_extensions=4.3.0
  - tzdata=2022c
  - ucrt=10.0.20348.0
  - unicodedata2=14.0.0
  - vc=14.2
  - vs2015_runtime=14.29.30139
  - wcwidth=0.2.5
  - wheel=0.37.1
  - xgboost=1.6.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zstd=1.5.2
