name: telecomChurn
channels:
  - defaults
  - conda-forge
dependencies:
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - brotlipy=0.7.0
  - ca-certificates=2022.07.19
  - catalogue=2.0.7
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - colorama=0.4.5
  - cryptography=37.0.1
  - cycler=0.11.0
  - cymem=2.0.6
  - cython=0.29.30
  - cython-blis=0.7.7
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - freetype=2.10.4
  - gensim=4.1.2
  - glib=2.69.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=3.3
  - intel-openmp=2022.0.0
  - ipykernel=6.9.1
  - ipython=8.4.0
  - jedi=0.18.1
  - jinja2=3.0.3
  - joblib=1.1.0
  - jpeg=9e
  - jupyter_client=7.2.2
  - jupyter_core=4.10.0
  - kiwisolver=1.4.2
  - langcodes=3.3.0
  - lerc=3.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=12.0.0
  - libdeflate=1.8
  - libffi=3.4.2
  - libiconv=1.16
  - liblapack=3.9.0
  - libogg=1.3.5
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.4.0
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - markupsafe=2.1.1
  - matplotlib=3.3.3
  - matplotlib-base=3.3.3
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - murmurhash=1.0.7
  - nest-asyncio=1.5.5
  - networkx=2.7.1
  - numpy=1.22.0
  - openssl=1.1.1q
  - packaging=21.3
  - pandas=1.1.4
  - parso=0.8.3
  - pathy=0.6.1
  - pcre=8.45
  - pickleshare=0.7.5
  - pillow=9.2.0
  - pip=22.1.2
  - ply=3.11
  - preshed=3.0.6
  - prompt-toolkit=3.0.20
  - pure_eval=0.2.2
  - pycparser=2.21
  - pydantic=1.9.0
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python_abi=3.8
  - pytz=2022.1
  - pywin32=302
  - pyzmq=23.2.0
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - requests=2.28.1
  - scikit-learn=1.1.1
  - scipy=1.7.3
  - seaborn=0.11.0
  - setuptools=58.0.4
  - shellingham=1.3.1
  - sip=6.6.2
  - six=1.16.0
  - smart_open=5.2.1
  - spacy=3.3.1
  - spacy-legacy=3.0.9
  - spacy-loggers=1.0.1
  - sqlite=3.39.2
  - srsly=2.4.3
  - stack_data=0.2.0
  - tbb=2021.5.0
  - thinc=8.0.15
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.64.0
  - traitlets=5.1.1
  - typer=0.4.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - urllib3=1.26.11
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wasabi=0.9.1
  - wcwidth=0.2.5
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - xz=5.2.5
  - zeromq=4.3.4
  - zlib=1.2.12
  - zstd=1.5.2
